# Title: openobserve
# Description: OpenObserve is a simple yet sophisticated log search, infrastructure monitoring, and APM solution
# Note: 
# Icon URL: https://openobserve.ai/favicon.svg
# URL: https://openobserve.ai

services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: "foo@bar.com"
      ZO_ROOT_USER_PASSWORD: "foobar"
    ports:
      - "5080:5080"
      - "5514:5514/tcp" # syslog tcp
      - "5514:5514/udp" # syslog udp
    volumes:
      - data:/data
volumes:
  data:
