# Title: techno-broadlink
# Description: A Docker container for BroadLink devices that hosts an HTTP Web API and a UI to send commands to devices on your local network
# Note: 
# Icon URL: 
# URL: https://github.com/techno-tim/techno-broadlink

services:
  techno-broadlink:
    image: timothystewart6/techno-broadlink
    environment:
      - HOST_IP=your.docker.host.ip
    ports:
      - "10981:10981"
    volumes:
      - config:/app/config
    network_mode: "host"

volumes:
  config:
